async check vote and add StopVote
OpenAtomFoundation/xupercore pull request #393
Opened 2022-12-22 07:51 UTC by godeamon

2022-12-23 04:01 UTC, zhugelianglongming requested changes
1. 避免遍历 map 同时删除
2. 优化 key 策略
3. 优化函数原型

2022-12-23 04:01 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +	err = ctx.Put(XTokenContract, key, value)
`return ctx.Put(XTokenContract, key, value)`

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +		for pidstr, amount := range pid2amount {
也不是所有的都必须驼峰，内部的一些临时变量，简单一些更方便，类似 chainName，如果缩写写成 cname 会比 cName 更好。

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			pid, _ := big.NewInt(0).SetString(pidstr, 10)
我觉得如果再其他入口能保证不会有err，在内部使用时不用处理err，前提是在其他其他保证这些数据没问题。

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			if p.Status == ProposalVoting && amount.Cmp(max) > 0 {
虽然这个数据目前只会有一个，但是我觉得你说的很对哈哈。

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_manager.go
> +		// QueryTopic:         x.QueryTopic,
ok

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +func (x *Contract) StopVote(ctx contract.KContext) (*contract.Response, error) {
这个合约名字是  XToken，所以我都用 x 了而非 c。

2022-12-23 07:07 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +	proposalEffectiveAmount := t.GenesisProposal.ProposalEffectiveAmount
下面应该也会用到，但是我还没写。。

2022-12-27 02:50 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +		for pidstr, amount := range pid2amount {
> 也不是所有的都必须驼峰，内部的一些临时变量，简单一些更方便，类似 chainName，如果缩写写成 cname 会比 cName 更好。

驼峰命名这个主要是看命名是否带来一些价值。比如是否降低了断词理解的成本？是否更符合大多数参与者的习惯？规范说到底还是为了更高效而服务的，如果不是，那么说明应该调整规范了。

对于临时变量，我个人的见解和经验：
- 如果是为了获得更简短的书写，在不存在歧义的情况下，`name`也可以是一个不错的临时变量名
- 若上下文存在其他 name，那添加 `c`或`chain`前缀，可作为区别之用，都是不错的选择。
- 如果觉得表意还不够明确，还可以再申明处再添加相应的注释

不过就`cname`和`cName`来表达 chainName而言，我会比较推荐`cName`，因为`cname`一般在会第一反应到 DNS中的专有名词，另外对于 name 这个概念的断词，需要略一判断后确认，理解成本高一丢丢。
一个可能不太合适的例子，比如`chainHeap` `cHeap` `cheap`(便宜的)。当然具体情况也具体分析。

2022-12-27 02:56 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			pid, _ := big.NewInt(0).SetString(pidstr, 10)
也可以的，这种情况一般建议注释说明“此处xx 原因，不存在错误，故不处理”的注释。另外开启 lint 后，需要显式的向检查程序此处跳过错误处理判断。

另外像我们代码库多处这么使用的话，建议可以在合适的 README 中简单说明下，比如“本代码库中对于 big 库的 xxx 时候，因 xxx 原因，默认不做错误处理”。

这样对于未来的开发者，在碰到这个疑问的时候，新参与的开发者们可以再代码库中找到这么做的原因，以及判断自己新增或修改的代码需要如何处置。当然，这部分就属于锦上添花的考虑了。

2022-12-27 03:05 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +func (x *Contract) StopVote(ctx contract.KContext) (*contract.Response, error) {
这有个小问题可以探讨下：xtoken 包下，如果定义了多个类，那么按这个逻辑，这些 receiver 是否都叫 x 。那么在不同类的函数中，如何自启发式的暗示当前类信息，对于 `x` 来说，他带来了什么价值？
这个感觉有点像退化到 java 的 this 指针。

2022-12-27 03:08 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_manager.go
>  		CheckVote:          x.CheckVote,
BTW，我发现 xtoken 包下，不少文件还使用`xtoken_` 前缀，有点冗余，不过看来是历史原因了。

2022-12-27 08:52 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +		for pidstr, amount := range pid2amount {
我觉得这个要结合上下文，比如在这个系统中，和链名字相关的代码，写 cname 也肯定能理解，但是如果是 cHeap 和 cheap 肯定是 cHeap，cheap这个单词大家都很熟悉。我觉得这个问题没必要完全按照驼峰，你看Go源码这种情况也是很多的。

2022-12-27 08:54 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			pid, _ := big.NewInt(0).SetString(pidstr, 10)
现在咱们的代码不是很规范，如果现在使用golint你会发现很多都不合适，很多代码从诞生就没有改过。。。

2022-12-27 08:55 UTC, godeamon commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +func (x *Contract) StopVote(ctx contract.KContext) (*contract.Response, error) {
我这个contract类可以理解成一个 xtoken 里面最主要的代表，所以我写了 x。写this也好，self也好，还是首字母或者多个单词首字母缩写，我觉得如果能表达清楚最好。

2023-01-03 03:26 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +		for pidstr, amount := range pid2amount {
> 在这个系统中，和链名字相关的代码，写 cname 也肯定能理解

支持

2023-01-03 08:29 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			pid, _ := big.NewInt(0).SetString(pidstr, 10)
那尽量保证新增的代码是规范的呀，不应该因为历史问题，又引入新的问题。

2023-01-04 06:34 UTC, gaoweibupt approved these changes

2023-01-04 07:24 UTC, zhugelianglongming requested changes
1. 建议补充单测
2. 建议处理或说明异常分支
3. 删除无用注释
4. 优化实现

2023-01-04 07:24 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +		if pidMap == nil {
建议 else 块外移一层，优化代码层级

2023-01-04 07:24 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +	if err != nil {
可省略 err 的返回前判断

2023-01-04 07:24 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +func (x *Contract) StopVote(ctx contract.KContext) (*contract.Response, error) {
> contract类可以理解成一个 xtoken 里面最主要的代表

如果是为了表达这个内容，x 作为 receiver 的方式还是比较隐晦的。个人建议也可以考虑使用其他的方式，比如：
- 在 xtoken 包的 README 中说明核心类信息
- 在 contract 类的类注释中说明其重要性

2023-01-04 08:27 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_contract.go
> +			pid, _ := big.NewInt(0).SetString(pidstr, 10)
//nolint: staticcheck

2023-01-04 09:00 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +		if pidMap == nil {
```
pidMap, ok := proposalMap[topic]
if !ok {
  return
}
if len(pid) == 0 {
  return 
}

pidMap babababa
```

2023-01-04 13:14 UTC, zhugelianglongming approved these changes
Acceptable for me

2023-01-16 02:41 UTC, zhugelianglongming commented on kernel/engines/xuperos/xtoken/xtoken_propose.go
> +func (c *Contract) StopVote(ctx contract.KContext) (*contract.Response, error) {
Unit test is recommended.

2023-01-30 03:21 UTC, merged