add create empty blocks config for single consensus
OpenAtomFoundation/xupercore pull request #432
Opened 2023-02-15 03:04 UTC by godeamon

2023-02-15 03:16 UTC, zhugelianglongming requested changes
建议更正字段名，优化实现位置

2023-02-15 03:16 UTC, zhugelianglongming commented on example/xchain/conf/engine.yaml
> +DisableEmyptBlocks: false
和其他配置一样，使用小写驼峰格式？

2023-02-15 03:16 UTC, zhugelianglongming commented on kernel/engines/xuperos/config/config.go
> +	DisableEmyptBlocks            bool    `yaml:"DisableEmyptBlocks,omitempty"`
`DisableEmyptBlocks` -> `DisableEmptyBlocks`

2023-02-15 03:16 UTC, zhugelianglongming commented on kernel/engines/xuperos/miner/miner.go
> +				return err
对于挖矿条件的判断，实现在`m.mining(ctx)`中可读性会不会更好一些？

2023-02-15 03:21 UTC, zhugelianglongming commented on kernel/engines/xuperos/miner/miner.go
> +			if consensusStatus.GetConsensusName() == "single" {
推荐抽取常量 ConsensusSingle

2023-02-15 08:49 UTC, godeamon commented on kernel/engines/xuperos/miner/miner.go
> +				return err
m.mining(ctx)  已经开始挖矿了，所以我放到外面了。

2023-02-17 02:54 UTC, zhugelianglongming commented on kernel/engines/xuperos/miner/miner.go
> +				return err
主要是有个疑问：`mining()` 实现的第一部分为"共识挖矿前处理"的定义是什么？打包区块前的判断逻辑，根据什么判断要放在`mining()`的函数头部 还是 函数调用前？

2023-02-17 02:55 UTC, zhugelianglongming commented on kernel/engines/xuperos/miner/miner.go
> +				return err
还有一个疑问是：空块判断算不算是 `ProcessBeforeMiner`？

2023-02-17 03:04 UTC, zhugelianglongming commented on kernel/engines/xuperos/miner/miner.go
> +				return err
我有一点建议是：
- 上层调用的时候，在确认是挖矿状态后，就只负责调用挖矿函数。
- 至于挖矿的前置处理、特殊判断（比如空块判断）等，可以在挖矿过程中，分阶段处理。

更具体的，在这里，我可能会建议实现在[m.packBlock](https://github.com/OpenAtomFoundation/xupercore/blob/master/kernel/engines/xuperos/miner/miner.go#L335)
相当于对区块大小的上限和下限分别进行判断处理。

2023-02-17 03:05 UTC, godeamon commented on kernel/engines/xuperos/miner/miner.go
> +				return err
共识这些接口开源文档里都有

2023-02-17 07:24 UTC, zhugelianglongming approved these changes
Functionally acceptable

2023-11-23 06:15 UTC, closed without merging