add update system config contracts
OpenAtomFoundation/xupercore pull request #444
Opened 2023-03-16 07:41 UTC by superlitian

## UpdateGasPrice
### usage
```json
{
    "args" : {
        "min_vote_percent": "51", 
        "stop_vote_height": "20" 
    },
    "trigger": {
        "height": 25, 
        "module": "xkernel",
        "contract": "$updateConfig",
        "method": "updateGasPrice",
        "args" : {
            "gas_price": {
                "cpu_rate": 1,
                "mem_rate": 1,
                "disk_rate": 2,
                "xfee_rate": 2
            }
        }
    }
}
```

## UpdateMaxBlockSize
### usage
```json
{
    "args" : {
        "min_vote_percent": "51", 
        "stop_vote_height": "20" 
    },
    "trigger": {
        "height": 25, 
        "module": "xkernel",
        "contract": "$updateConfig",
        "method": "updateGasPrice",
        "args" : {
            "maxBlockSize":  12222222
        }
    }
}
```
**rollBackUpdateGasPrice and rollBackUpdateMaxBlockSize 保证区块回滚时数据一起回滚。**

2023-03-16 08:19 UTC, godeamon commented on bcs/ledger/xledger/state/state.go
> +		if output.Bucket == "proposal" {
proposal 字符串直接引用 proposla 合约内的字符串变量

2023-03-16 08:19 UTC, godeamon commented on bcs/ledger/xledger/state/state.go
> +			case "updateMaxBlockSize":
最好也是引用系统合约内的变量

2023-03-16 08:21 UTC, godeamon commented on kernel/contract/proposal/propose/propose_contract.go
> +		fmt.Printf("call proposal err: %v", err)
删除打印

2023-03-16 08:22 UTC, godeamon commented on kernel/contract/proposal/utils/types.go
> +	UpdateConfigKernelContract = "$updateConfig"
合约名字不合适，chain_config 或者再想想其他的

2023-03-16 08:24 UTC, godeamon commented on kernel/engines/xuperos/update_config/update_config.go
添加单测

2023-03-16 14:57 UTC, zhugelianglongming requested changes

2023-03-16 14:57 UTC, zhugelianglongming commented on bcs/ledger/xledger/state/meta/meta.go
> +	newMeta.GasPrice = oldGasPrice
1. 2 次更新 batch 的逻辑相似，建议抽取函数隐藏细节。 避免重复代码的同时，提高代码可读性。
2. `newMeta` 和 `先保存旧的数据` 的含义冲突

如：
`putGasPriceInBatch(batch kvdb.Batch, key string, gasPrice*protos.GasPrice)` 
`richBatch.putGasPrice(key string, gasPrice*protos.GasPrice)`

2023-03-16 14:57 UTC, zhugelianglongming commented on bcs/ledger/xledger/state/state.go
> +		if output.Bucket == "proposal" {
+1

2023-04-28 06:42 UTC, zhugelianglongming requested changes

2023-04-28 06:42 UTC, zhugelianglongming commented on bcs/ledger/xledger/state/meta/meta.go
>  	tmpMeta := &pb.UtxoMeta{}
为什么还需要在保存的外部进行默认结构的创建和克隆？是不是可以在`putGasPriceInBatch`内创建结构，对于函数调用方，避免冗余信息的保留。

2023-04-28 06:42 UTC, zhugelianglongming commented on bcs/ledger/xledger/state/meta/meta.go
> +func putGasPriceInBatch(batch kvdb.Batch, tmpMeta *pb.UtxoMeta, key []byte, gasPrice *protos.GasPrice) error {
put 类函数的实现，和忌讳对于输入参数有额外修改（副作用）。
如实现必要，要在注释中说明，让调用方注意到。一般情况下都可以避免，对于有必要的修改，在函数外显示操作，然后进行 put。
这个函数有必要对tmpMeta进行修改吗？

2023-04-28 06:42 UTC, zhugelianglongming commented on bcs/ledger/xledger/state/meta/meta.go
> +func putMaxBlockSizeInBatch(batch kvdb.Batch, tmpMeta *pb.UtxoMeta, key []byte, maxBlockSize int64) error {
同上，可以考虑对于需要保存的格式信息，限制在函数范围内，调用方不需要知道具体的对象，保证提供必要的信息即可。

2024-01-24 10:03 UTC, closed without merging