增加链接重试的机制
OpenAtomFoundation/xupercore pull request #447
Opened 2023-05-26 06:20 UTC by springrain

XPOA共识时,出现xfront连接数过多的问题,增加重试相关参数,避免状态异常重复创建链接

2023-05-26 09:29 UTC, zhugelianglongming requested changes

2023-05-26 09:29 UTC, zhugelianglongming commented on bcs/network/p2pv1/conn.go
> +			// 退避策略：指数退避
注释与实现不一致：`指数退避`

2023-05-26 09:29 UTC, zhugelianglongming commented on bcs/network/p2pv1/conn.go
> +	// 加锁创建
为什么只是 retry 的期间加锁？

2023-06-06 04:00 UTC, springrain commented
这个pr本意是为了防止xuperchain频繁创建连接,在XPOA共识环境出现创建的1万多个连接的情况.但是这个PR造成了出块不稳定,先关闭了.

2023-06-06 04:00 UTC, closed without merging